import { describe, expect, it } from "vitest";

import { hashPassword, verifyPassword } from "../utils/auth.js";

describe("password hash compatibility", () => {
  it("verifies passwords generated by the supported scrypt helper", async () => {
    const hash = await hashPassword("local-test-password");

    await expect(verifyPassword("local-test-password", hash)).resolves.toBe(true);
    await expect(verifyPassword("wrong-password", hash)).resolves.toBe(false);
  });
});
